# coding=utf-8
# ======================================
# File: strategy_codegen.py
# Author: Jackie PENG
# Contact: jackie.pengzhao@gmail.com
# Created: 2026-08-29
# Desc:
# qteasy AI 阶段 D：Spec → 策略骨架写盘。
# ======================================

"""按模板将 StrategySpec 写成用户目录策略源码。"""

from __future__ import annotations

import difflib
from pathlib import Path
from typing import Any, Callable, Dict, Optional

from ..contracts import (
    SkillError,
    SkillMetadata,
    SkillResult,
    SkillSideEffects,
    StrategySpec,
    new_run_id,
)
from ..memory_store import MemoryStore
from .strategy_spec import SMA_CROSS_TEMPLATE_ID, resolve_spec_from_inputs

_SMA_CROSS_TEMPLATE = '''# coding=utf-8
"""Generated by qteasy-ai StrategyBuilder (template {template_id})."""

from __future__ import annotations

import numpy as np
import qteasy as qt
from qteasy import Parameter, StgData


def _sma_cross_signal(close: np.ndarray, fast: int, slow: int) -> float:
    """双均线交叉信号，返回 PS 语义（+1 金叉 / -1 死叉 / 0 持有）。"""

    from qteasy.tafuncs import sma

    if close is None or getattr(close, "shape", [0])[0] < max(int(fast), int(slow)) + 2:
        return 0.0
    s_ma = sma(close, int(slow))
    f_ma = sma(close, int(fast))
    s_today, s_last = s_ma[-1], s_ma[-2]
    f_today, f_last = f_ma[-1], f_ma[-2]
    if (f_last <= s_last) and (f_today >= s_today):
        return 1.0
    if (f_last >= s_last) and (f_today <= s_today):
        return -1.0
    return 0.0


class {class_name}(qt.RuleIterator):
    """生成的双均线择时策略（RuleIterator）。"""

    def __init__(self, **kwargs):
        super().__init__(
            pars=[
                Parameter({fast_range}, name='fast', par_type='int', value={fast}),
                Parameter({slow_range}, name='slow', par_type='int', value={slow}),
            ],
            name='{class_name}',
            description='Generated dual-MA cross timing strategy',
            data_types=StgData('close', freq='d', asset_type='ANY', window_length={window_length}),
            **kwargs,
        )

    def realize(self):
        fast, slow = self.get_pars('fast', 'slow')
        close = self.get_data('close_ANY_d')
        return _sma_cross_signal(close, fast=fast, slow=slow)
'''


def _par_value(spec: StrategySpec, name: str, default: int) -> int:
    """读取 Spec 参数默认值。"""

    for item in spec.parameters:
        if str(item.get("name")) == name:
            return int(item.get("default", default))
    return default


def _par_range(spec: StrategySpec, name: str, fallback: tuple) -> tuple:
    """读取 Spec 参数范围。"""

    for item in spec.parameters:
        if str(item.get("name")) == name:
            raw = item.get("range") or list(fallback)
            if isinstance(raw, (list, tuple)) and len(raw) >= 2:
                return (int(raw[0]), int(raw[1]))
    return fallback


def render_sma_cross_source(spec: StrategySpec) -> str:
    """将 SMA 交叉 Spec 渲染为 Python 源码。"""

    fast = _par_value(spec, "fast", 20)
    slow = _par_value(spec, "slow", 60)
    window_length = int(spec.window_length or (slow + 5))
    class_name = spec.class_name or "GeneratedSmaCross"
    fast_range = _par_range(spec, "fast", (5, 80))
    slow_range = _par_range(spec, "slow", (20, 200))
    return _SMA_CROSS_TEMPLATE.format(
        template_id=SMA_CROSS_TEMPLATE_ID,
        class_name=class_name,
        fast=fast,
        slow=slow,
        fast_range=fast_range,
        slow_range=slow_range,
        window_length=window_length,
    )


def _safe_filename(class_name: str) -> str:
    """生成安全文件名。"""

    text = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in class_name)
    return f"{text or 'GeneratedSmaCross'}.py"


def _is_forbidden_write_path(path: Path) -> bool:
    """禁止写入 qteasy 安装包或仓内 examples。"""

    resolved = path.resolve()
    parts = [part.lower() for part in resolved.parts]
    if "site-packages" in parts and "qteasy" in parts:
        return True
    if "examples" in parts:
        return True
    return False


def build_strategy_codegen_hybrid_skill(
    strategies_dir: Optional[str] = None,
) -> tuple[SkillMetadata, Callable[..., dict]]:
    """构建 ``qt.ai.strategy.codegen_hybrid``。

    Parameters
    ----------
    strategies_dir : str, optional
        测试注入的写盘目录；默认 ``MemoryStore.strategies_dir``。

    Returns
    -------
    tuple
        ``(SkillMetadata, handler)``。
    """

    metadata = SkillMetadata(
        name="qt.ai.strategy.codegen_hybrid",
        version="0.1.0",
        summary="Generate a RuleIterator dual-MA skeleton into .qteasy/ai/strategies/ (never writes the qteasy package).",
        inputs_schema={
            "spec": {"type": "object", "required": False},
            "overwrite": {"type": "boolean", "required": False},
        },
        outputs_schema={"strategy_path": "str", "artifacts": "list"},
        side_effects=SkillSideEffects(
            filesystem_write=True,
            description="writes generated strategy source under .qteasy/ai/strategies/",
        ),
        required_capabilities=[],
        qteasy_entrypoints=["qteasy.RuleIterator", "qteasy.Parameter", "qteasy.StgData"],
        skill_kind="api",
    )

    def handler(
        spec: Any = None,
        overwrite: bool = False,
        strategy_path: str = "",
        upstream_payload: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> dict:
        run_id = new_run_id()
        spec_raw = resolve_spec_from_inputs(
            spec=spec, upstream_payload=upstream_payload, **kwargs
        )
        inputs_echo = {"overwrite": bool(overwrite), "spec_template": spec_raw.get("template_id")}
        if not spec_raw:
            result = SkillResult(
                ok=False,
                skill_name=metadata.name,
                run_id=run_id,
                inputs_echo=inputs_echo,
                error=SkillError(
                    code="SPEC_MISSING",
                    message="codegen_hybrid requires a StrategySpec payload.",
                ),
            )
            return result.to_dict()
        spec_obj = StrategySpec.from_dict(spec_raw)
        if spec_obj.template_id != SMA_CROSS_TEMPLATE_ID:
            result = SkillResult(
                ok=False,
                skill_name=metadata.name,
                run_id=run_id,
                inputs_echo=inputs_echo,
                error=SkillError(
                    code="UNKNOWN_TEMPLATE_ID",
                    message=(
                        f"Unknown template_id: {spec_obj.template_id}. "
                        f"This stage only supports {SMA_CROSS_TEMPLATE_ID}."
                    ),
                ),
            )
            return result.to_dict()
        target_dir = Path(strategies_dir) if strategies_dir else MemoryStore().strategies_dir
        target_dir.mkdir(parents=True, exist_ok=True)
        filename = _safe_filename(spec_obj.class_name or "GeneratedSmaCross")
        target = Path(strategy_path) if str(strategy_path).strip() else (target_dir / filename)
        target = target.expanduser()
        if _is_forbidden_write_path(target):
            result = SkillResult(
                ok=False,
                skill_name=metadata.name,
                run_id=run_id,
                inputs_echo=inputs_echo,
                error=SkillError(
                    code="FORBIDDEN_WRITE_PATH",
                    message="Generated strategy source must not be written into the qteasy package or examples/.",
                    details={"path": str(target)},
                ),
            )
            return result.to_dict()
        source = render_sma_cross_source(spec_obj)
        artifacts = []
        if target.exists() and not overwrite:
            old_text = target.read_text(encoding="utf-8")
            diff_lines = list(
                difflib.unified_diff(
                    old_text.splitlines(),
                    source.splitlines(),
                    fromfile=str(target),
                    tofile=str(target) + ".proposed",
                    lineterm="",
                )
            )
            diff_text = "\n".join(diff_lines)
            artifacts.append({"kind": "diff", "path": str(target), "content": diff_text})
            result = SkillResult(
                ok=False,
                skill_name=metadata.name,
                run_id=run_id,
                inputs_echo=inputs_echo,
                artifacts=artifacts,
                payload={"strategy_path": str(target), "spec": spec_obj.to_dict()},
                error=SkillError(
                    code="FILE_EXISTS_CONFIRM_REQUIRED",
                    message="Target strategy file already exists. Review the diff and confirm overwrite.",
                    details={"path": str(target)},
                ),
            )
            return result.to_dict()
        if target.exists() and overwrite:
            bak = target.with_suffix(target.suffix + ".bak")
            bak.write_text(target.read_text(encoding="utf-8"), encoding="utf-8")
            artifacts.append({"kind": "backup", "path": str(bak)})
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")
        artifacts.append({"kind": "strategy_source", "path": str(target)})
        result = SkillResult(
            ok=True,
            skill_name=metadata.name,
            run_id=run_id,
            inputs_echo=inputs_echo,
            artifacts=artifacts,
            payload={
                "strategy_path": str(target),
                "class_name": spec_obj.class_name or "GeneratedSmaCross",
                "spec": spec_obj.to_dict(),
            },
            data_summary={"strategy_path": str(target), "bytes": target.stat().st_size},
        )
        return result.to_dict()

    return metadata, handler
